/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cri1;
import java.util.Random;


/**
 *
 * @author Lalith
 */
public class bowl extends javax.swing.JFrame  {
public static int b;

Random rand = new Random();

//}

    /**
     * Creates new form bowl
     */
    public bowl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cricket");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select One Of The Following Number :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-80, 0, 720, 140);

        j1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(j1);
        j1.setBounds(620, 70, 490, 60);

        l11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(l11);
        l11.setBounds(900, 180, 150, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Opponent Score :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 150, 300, 100);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(270, 330, 70, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(270, 220, 70, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 120, 70, 60);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(170, 450, 80, 70);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 220, 70, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 330, 70, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 120, 70, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\c\\bowl.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}
        int a=rand.nextInt((7));
        if(a==0){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
             
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}
        int a=rand.nextInt((7));
        if(a==1){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
       if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}
        int a=rand.nextInt((7));
        if(a==2){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}
        int a=rand.nextInt((7));
        if(a==3){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}
        int a=rand.nextInt((7));
        if(a==4){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d); 
}
        int a=rand.nextInt((7));
        if(a==5){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       bat ba=new bat();
int d=ba.c;
criii s=new criii();
int x=s.y;
if(x==1||x!=2)
{
    j1.setText("Your Score is: "+d);
}

        int a=rand.nextInt((7));
        if(a==6){
            l11.setText(""+b);
            if(x==1){
            new Cong().setVisible(true);
            this.setVisible(false);
            }
            else if(x==2)
            {
                new bat().setVisible(true);
                this.setVisible(false);
            }
            else{
                new Cong().setVisible(true);
                this.setVisible(false);
            }
        }
        else{b=b+a;
        l11.setText(""+b);
        if(b>d&&(x==1||x!=2))
        {
            new Cong().setVisible(true);
            this.setVisible(false);
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bowl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bowl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bowl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bowl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bowl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l11;
    // End of variables declaration//GEN-END:variables
}
